# Generated by Django 4.2.30 on 2026-05-01 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitedguest',
            name='current_guests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invitedguest',
            name='rsvped',
            field=models.BooleanField(default=False),
        ),
    ]
