# Generated by Django 4.2.30 on 2026-05-02 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0002_invitedguest_current_guests_invitedguest_rsvped'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitedguest',
            name='partner_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='invitedguest',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
