# Generated by Django 4.2.30 on 2026-05-02 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0003_invitedguest_partner_name_invitedguest_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvpguest',
            name='guest_type',
            field=models.CharField(choices=[('adult', 'Adult'), ('child', 'Child')], default='adult', max_length=10),
        ),
        migrations.AlterField(
            model_name='rsvpguest',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='rsvpguest',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
